data:
  Domain-Seeds:
    - d3f.me
  Good-IPs:
    - 5.9.29.41
    - 2a01:4f8:161:112e::2
    - 92.222.78.150
    - 2001:16b8:1d01:6ad7:3681:c4ff:fe3b:86c7
  Homoglyph-Domains:
    - def.me
    - d3ff.me
    - d33f.me
  DNS-Resolvers:
    - 1.1.1.1
    - 8.8.8.8
    - 9.9.9.9

run:
  - discover Domains and IPs:
      seeds: use Domain-Seeds
      resolvers: use DNS-Resolvers
    find:
      - IPs
      - Domains
      - DNS-Entries
    expect:
      - no added IPs, otherwise alert high
      - no added Domains, otherwise alert high
      - no added DNS-Entries, otherwise alert high
      - all IPs in Good-IPs, otherwise alert high
      
  - discover Domains and IPs:
      seeds: use Homoglyph-Domains
      resolvers: use DNS-Resolvers
    find:
      - Domains as Homoglyph-Matches
    expect:
      - no Homoglyph-Matches, otherwise alert high

      
  - scan Ports:
      protocols:
        - tcp
      ports: 80,443
      ips: use IPs
    find:
      - Host-Ports
      - HTTP-IPs
      - HTTPS-IPs
    expect:
      - no added Host-Ports, otherwise alert very high
      
  - scan Webservers:
      ips: use HTTP-IPs and HTTPS-IPs
      domains: use Domains
    find:
      - Web-Origins
      - TLS-Web-Origins
      - TLS-Domains
    expect:
      - no added Web-Origins, otherwise alert high

  - scan TLS Settings:
      domains: use TLS-Domains
      allowed_grades:
        - 'A'
        - 'A+'
    find:
      - TLS-Grade-Error
      - TLS-Grade-Fail
      - TLS-Grade-Success-IPs
    expect:
      - no TLS-Grade-Fail, otherwise alert high
      - no TLS-Grade-Error, otherwise alert high
      - all TLS-Grade-Success-IPs in Good-IPs, otherwise alert high
          
  - scan Web Security Settings:
      hosts: use Web-Origins
    find:
      - Non-TLS-URLs
      - Missing-HTTPS-Redirect-URLs
      - Redirect-to-non-HTTPS-URLs
      - Disallowed-Header-URLs
      - Missing-Header-URLs
      - Disallowed-Method-URLs
      - Insecure-Cookie-URLs
    expect:
      - no Non-TLS-URLs, otherwise alert high
      - no Missing-HTTPS-Redirect-URLs, otherwise alert high
      - no Redirect-to-non-HTTPS-URLs, otherwise alert high
      - no Disallowed-Header-URLs, otherwise alert medium
      - no Missing-Header-URLs, otherwise alert medium
      - no Disallowed-Method-URLs, otherwise alert medium
      - no Insecure-Cookie-URLs, otherwise alert medium
      
  
      
output:
  version: 1
  formatters:
    default:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    alert:
      format: "[%(asctime)s]\n%(levelname)s: %(message)s"
  root:
    level: DEBUG
    handlers:
      - console
      - file_debug
      - file_alerts
  handlers:
    console:
      class : logging.StreamHandler
      formatter: default
      level   : WARNING
      stream  : ext://sys.stdout
    file_debug:
      class : logging.FileHandler
      formatter: default
      filename: bogosec.debug.log
      level   : DEBUG
    file_alerts:
      class : logging.FileHandler
      formatter: alert
      filename: bogosec.alerts.log
      level   : ALERT_LOW
