data:
  Origins:
    - url: https://yes.com/
      ip: 51.4.194.141
      domain: yes.com

run:
  - discover Hidden Paths:
      origins: use Origins
      recursion_depth: 3
    find:
      - Hidden-Paths
      - Hidden-Pages