data:
  Domain-Seeds:
    - domain: flame16.synology.me
  DNS-Resolvers:
    - ip: 8.8.8.8

run:
  - discover Domains and IPs:
      seeds: use Domain-Seeds
      resolvers: use DNS-Resolvers
    find:
      - IPs
      - Domains
      - DNS-Entries
  - scan Ports:
      protocols:
        - tcp
      ports: 80,443,8000,8001
      ips: use IPs
    find:
      - Host-Ports
      - HTTP-Ports
      - HTTPS-Ports
  - discover Webservers:
      ips: use Host-Ports
      domains: use Domains
      ports:
        - port: 80
        - port: 443
        - port: 8000
        - port: 8001
    find:
      - Insecure-Origins
      - Secure-Origins
      - TLS-Domains
  - discover Linked Paths:
      origins: use Insecure-Origins and Secure-Origins
    find:
      - Linked-Paths
      - Linked-Pages
  - discover Hidden Paths:
      origins: use Insecure-Origins and Secure-Origins
      linked_paths: use Linked-Paths
    find:
      - Hidden-Paths
      - Hidden-Pages
  - scan Information Leakage:
      pages: use Linked-Pages and Hidden-Pages
    find:
      - Leakages